---
title: "Pamguard Processing"
editor: visual
---

# Summary

[Pamgaurd version 2.02.14](https://www.pamguard.org/releases/download.html) was used to process all drifting acoustic buoy recordings in order to collect click data for both sperm whales and beaked whales. Analysis of these data will differ on a species by species basis.

# Beaked Whales

Full bandwidth recordings were run through a suite of click detectors in [PAMguard](https://www.pamguard.org/) to pull out clicks corresponding to specific frequency bands. Prior to this, recordings were decimated to 288kHz. A 10kHz high pass filter was applied to the decimated recordings and then passed to the click detector. PAMguard settings files can be found [here](https://github.com/SAEL-SWFSC/CalCurCEAS-2024-Drifter-Analysis/tree/main/_data/BeakedWhales/Pamguard/PamgaurdSettings).

# Sperm Whales

### PAMGuard

Full bandwidth recordings were run through a suite of click detectors in PAMGuard to pull out clicks corresponding to specific frequency bands. Recordings were then decimated to 96kHz and run through whistle and moan detectors. PAMGuard settings files can be found [here](https://github.com/SAEL-SWFSC/CalCurCEAS-2024-Drifter-Analysis/tree/main/_data/SpermWhales/Pamguard/PamguardSettings).

### PAMpal

Following PAMGuard pre-processing, [PAMpal](https://taikisan21.github.io/PAMpal/) was used to create acoustic studies for all detections in each drift (code here - *input later*). The next step was to create event summary reports for all potential sperm whale click events (code here - *input later*). Lastly, these events will be manually validated as sperm whale click events or noise, and those validated detections will be used for further analysis.

## *Status:* 

*All data has been processed in PAMGuard. PAMpal analysis in progress*
